export const POKEMON_TYPE_COLORS = {
    'default': { label: 'Desconhecido', color: '#68A090' },
    'all': { label: 'Todos os tipos', color: '#333333' },
    'water': { label: 'Água', color: '#5090D6' },
    'dragon': { label: 'Dragão', color: '#0B6DC3' },
    'electric': { label: 'Elétrico', color: '#F4D23C' },
    'fairy': { label: 'Fada', color: '#EC8FE6' },
    'ghost': { label: 'Fantasma', color: '#5269AD' },
    'fire': { label: 'Fogo', color: '#FF9D55' },
    'ice': { label: 'Gelo', color: '#73CEC0' },
    'grass': { label: 'Grama', color: '#63BC5A' },
    'bug': { label: 'Inseto', color: '#91C12F' },
    'fighting': { label: 'Lutador', color: '#CE416B' },
    'normal': { label: 'Normal', color: '#919AA2' },
    'dark': { label: 'Noturno', color: '#5A5465' },
    'steel': { label: 'Metal', color: '#5A8EA2' },
    'rock': { label: 'Pedra', color: '#C5B78C' },
    'psychic': { label: 'Psíquico', color: '#FA7179' },
    'ground': { label: 'Terrestre', color: '#D97845' },
    'poison': { label: 'Venenoso', color: '#B567CE' },
    'flying': { label: 'Voador', color: '#89AAE3' },
};